# Generated by Django 3.0.4 on 2020-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('tasks_type', models.CharField(choices=[('specials', 'SPECIAL'), ('tricks', 'TRICKS')], default='specials', max_length=20)),
            ],
        ),
    ]
